name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run seasonal header update script
        run: |
          python scripts/seasonal-readme-updater.py

      - name: Run daily quote update script
        run: |
          python scripts/update-quote.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Stage and commit changes
          git add README.md
          git commit -m "docs(readme): update header and daily quote" || echo "No changes to commit"

          # Fetch the latest remote changes and reset to avoid conflicts
          git fetch origin
          git reset --soft origin/main

          # Push the changes (force if necessary)
          git push --force
